[package]
name = "grug-rs-proc-macro"
version = "0.1.1"
edition = "2024"
description = "Proc Macros for grug-rs"
license = "MIT"
repository = "https://github.com/lemonlambda/grug-rs"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full"] }
